### ISSUE TITLE
Fails while trying to find coefficients of cubic polynomial

### ISSUE THREAD

**Issue by SlashzeroOfficial** [lovasoa/lagrange-cpp#1]
I tried running the the program with the following points:
0 0
2 8
3 27
10 1000

The output obtained was 0 0 1 0 instead of the expected 0 0 0 1.
Could you take a look?

Thanks.

**Comment by lovasoa** [comment]
Sorry, but I cannot reproduce this bug. I get the expected `0 0 0 1`:

```sh
$ make
g++  -std=c++14   coeffs.cpp   -o coeffs
g++  -std=c++14   poly_exec.cpp   -o poly_exec
$ cat > points.txt
0 0
2 8
3 27
10 1000
$ ./coeffs < points.txt 
0
-1.77636e-15
0
1
```

**Comment by SlashzeroOfficial** [comment]
Sorry, my bad. I was storing the coefficients into an array and  messed up the indexing.
Thanks!
